server:
  port: ${PORT:9094}
  # added -----------
  forward-headers-strategy: framework
  tomcat:
      use-relative-redirects: true
  # ---------------------
  servlet:
    context-path: /

  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always


google:
  client-id: ${GOOGLE_CLIENT_ID}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:journal-service}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com


logging:
  level:
    root: ${LOG_ROOT_LEVEL:INFO}
    com.triphub.tripjournal: ${LOG_APP_LEVEL:INFO}

journal:
  enrichment:
    enabled: ${JOURNAL_ENRICHMENT_ENABLED:true}
  media-callbacks:
    enabled: ${JOURNAL_MEDIA_CALLBACKS_ENABLED:true}

# --- Weather config (top-level) ---
openweather:
  apiKey: ${OPENWEATHER_API_KEY}
  baseUrl: https://api.openweathermap.org
  units: metric



