server:
  port: ${PORT:9094}
  servlet:
    context-path: /

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:journal-service}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://trippass:9091
        #issuer-uri: ${OAUTH2_ISSUER_URI:https://accounts.google.com}
        #OR, if you don’t expose issuer metadata, use jwk-set-uri:
        # spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://trippass:9091/oauth2/jwks

logging:
  level:
    root: ${LOG_ROOT_LEVEL:INFO}
    com.triphub.tripjournal: ${LOG_APP_LEVEL:INFO}

journal:
  enrichment:
    enabled: ${JOURNAL_ENRICHMENT_ENABLED:true}
  media-callbacks:
    enabled: ${JOURNAL_MEDIA_CALLBACKS_ENABLED:true}

# --- Weather config (top-level) ---
openweather:
  apiKey: ${OPENWEATHER_API_KEY}
  baseUrl: https://api.openweathermap.org
  units: metric
